default: true
MD013: false  # line-length: Disable (too strict for documentation/URLs)
MD033: false  # no-inline-html: Disable (needed for centering/resizing images)
MD003:        # heading-style
  style: atx  # Enforce hash-style headers
